[build]
  command = "npm install && node ./node_modules/vite/bin/vite.js build"
  publish = "dist"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200